# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RF49hWLJ8k1k8l4s_6_fZf_lTPpeFWU-

Install Flask
"""

pip install flask

"""Creating The WebApp"""

from flask import Flask, request, render_template
from tensorflow.keras.models import load_model
from tensorflow.keras.preprocessing import image
import numpy as np

app = Flask(__name__)
model = load_model('skin_lesion_model.h5')

@app.route('/', methods=['GET', 'POST'])
def predict():
    if request.method == 'POST':
        img = image.load_img(request.files['file'], target_size=(128, 128))
        img_array = image.img_to_array(img) / 255.0
        img_array = np.expand_dims(img_array, axis=0)
        prediction = model.predict(img_array)
        predicted_class = np.argmax(prediction[0])
        class_labels = list(label_map.keys())
        return render_template('result.html', class=class_labels[predicted_class])
    return render_template('index.html')

if __name__ == '__main__':
    app.run(debug=True)

"""Input Design"""

<!DOCTYPE html>
<html>
<head>
    <title>Skin Skan</title>
</head>
<body>
    <h1>Upload an image of your skin lesion</h1>
    <form action="/" method="post" enctype="multipart/form-data">
        <input type="file" name="file">
        <input type="submit" value="Predict">
    </form>
</body>
</html>

"""Output Design"""

<!DOCTYPE html>
<html>
<head>
    <title>Prediction Result</title>
</head>
<body>
    <h1>Prediction: {{ class }}</h1>
    <a href="/">Back</a>
</body>
</html>

"""Run The App"""

python app.py